### ISSUE TITLE
在Windows上无法启动

### ISSUE THREAD

**Issue by Zxilly** [RikkaApps/FCM-for-Mojo-Server#15]
```
> ffm@0.7.0 start C:\mojowebqq\FCM-for-Mojo-Server
> node node/index.js

[FFM] client config file: client.json not exist, use empty data
[FFM] restart called...
[FFM] starting Mojo-Webqq...
[FFM] start Mojo-Webqq... args=C:\mojowebqq\FCM-for-Mojo-Server/perl/start.pl,--
node-port=5004,--openqq-port=5003
[FFM] ids =
[FFM] no https configuration found
[FFM] no basic auth configuration found
[FFM] listening 5005, 193.112.185.37
[FFM] exit with code: 1
[FFM] killing Mojo-Webqq...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 193.112.185.37:5005
    at Server.setupListenHandle [as _listen2] (net.js:1343:19)
    at listenInCluster (net.js:1401:12)
    at doListen (net.js:1510:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffm@0.7.0 start: `node node/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffm@0.7.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ghost\AppData\Roaming\npm-cache\_logs\2018-10-11T05_39_40_
602Z-debug.log
```

**Comment by Zxilly** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ffm@0.7.0~prestart: ffm@0.7.0
6 info lifecycle ffm@0.7.0~start: ffm@0.7.0
7 verbose lifecycle ffm@0.7.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle ffm@0.7.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\mojowebqq\FCM-for-Mojo-Server\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\cygwinroot\usr\local\bin;C:\cygwinroot\bin;C:\cygwinroot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ldaptools;C:\Program Files\QCloud\Monitor\Barad;%JAVA_HOME%\bin;C:\Program Files\Redis\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Users\Ghost\AppData\Roaming\npm
9 verbose lifecycle ffm@0.7.0~start: CWD: C:\mojowebqq\FCM-for-Mojo-Server
10 silly lifecycle ffm@0.7.0~start: Args: [ '/d /s /c', 'node node/index.js' ]
11 silly lifecycle ffm@0.7.0~start: Returned: code: 1  signal: null
12 info lifecycle ffm@0.7.0~start: Failed to exec start script
13 verbose stack Error: ffm@0.7.0 start: `node node/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid ffm@0.7.0
15 verbose cwd C:\mojowebqq\FCM-for-Mojo-Server
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error ffm@0.7.0 start: `node node/index.js`
22 error Exit status 1
23 error Failed at the ffm@0.7.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by haruue** [comment]
```
Error: listen EADDRNOTAVAIL 193.112.185.37:5005
```

会不会是端口被占用什么的呢。。。

**Comment by Zxilly** [comment]
@haruue 当然不是。。。这么奇怪的端口不会有其他程序用的QwQ

**Comment by Zxilly** [comment]
改了改代码解决了。。。

**Comment by WordlessEcho** [comment]
Please post some details about the problems and solutions to help others. Thanks.
